language: minimal
services: docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.2
before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

script:
  - docker --version
  - docker build -f udagram-api-feed/Dockerfile -t  viktohtimmy/udagram-api-feed:latest udagram-api-feed
  - docker build -f udagram-api-user/Dockerfile -t  viktohtimmy/udagram-api-user:latest udagram-api-user
  - docker build -f udagram-frontend/Dockerfile -t  viktohtimmy/udagram-frontend:latest udagram-frontend
  - docker build -f udagram-reverseproxy/Dockerfile -t  viktohtimmy/udagram-reverseproxy:latest udagram-reverse-proxy


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push viktohtimmy/udagram-api-feed:latest
  - docker push viktohtimmy/udagram-api-user:latest
  - docker push viktohtimmy/udagram-frontend:latest
  - docker push viktohtimmy/udagram-reverseproxy:latest