apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-backend-feed
  name: udagram-backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-backend-feed
